#!/usr/bin/env python3
"""Compatibility entry point for the corrected Starlink D2C coverage map.

The map now uses one centroid per TAC rather than plotting every TAC/ECI row as
an independent cell.  The full figure suite is generated by
``scripts/satellite_analysis_figures.py``.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

import cartopy.crs as ccrs
import matplotlib as mpl
import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.lines import Line2D
from shapely.geometry import shape


ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "satellites"
INVENTORY = DATA / "plmn_inventory.csv"
SUMMARY = DATA / "plmn_summary.csv"
CELLS = DATA / "cells"
BOUNDARIES = ROOT / "data" / "reference" / "ne_10m_admin_0_map_units.geojson"
DEFAULT_OUTPUT = ROOT / "paper" / "figs" / "satellite_world_map.pdf"

GROUP_ORDER = ["linked_candidate", "unresolved_signature", "direct_assignment", "onboard_control"]
STYLE = {
    "linked_candidate": {
        "label": "Source-linked D2C candidates",
        "color": "#6a3d9a",
        "marker": ".",
        "size": 0.45,
        "alpha": 0.12,
        "zorder": 2,
    },
    "unresolved_signature": {
        "label": "Unresolved signature matches",
        "color": "#e08214",
        "marker": "o",
        "size": 2.2,
        "alpha": 0.52,
        "zorder": 3,
    },
    "direct_assignment": {
        "label": "Direct satellite / NTN assignments",
        "color": "#1b8a70",
        "marker": "^",
        "size": 11.0,
        "alpha": 0.82,
        "zorder": 4,
    },
    "onboard_control": {
        "label": "Onboard / hybrid controls",
        "color": "#087f8c",
        "marker": "x",
        "size": 10.0,
        "alpha": 0.82,
        "zorder": 5,
    },
}


def inventory_rows() -> list[dict[str, str]]:
    with INVENTORY.open(newline="", encoding="utf-8") as f:
        rows = [row for row in csv.DictReader(f) if row["figure_include"] == "1"]
    if not rows:
        raise RuntimeError("No figure rows in the satellite inventory")
    missing = [row["plmn"] for row in rows if not (CELLS / f"{row['plmn']}.csv.gz").exists()]
    if missing:
        raise FileNotFoundError(f"Missing cell snapshots: {', '.join(missing)}")
    return rows


def world_geometries() -> list:
    collection = json.loads(BOUNDARIES.read_text(encoding="utf-8"))
    return [shape(feature["geometry"]) for feature in collection["features"]]


def group_counts() -> dict[str, int]:
    summary = pd.read_csv(SUMMARY)
    return (
        summary.groupby("figure_group")["valid_latest_positions"]
        .sum()
        .astype(int)
        .to_dict()
    )


def plot_cell_file(ax, plate, path: Path, group: str) -> int:
    style = STYLE[group]
    plotted = 0
    for chunk in pd.read_csv(
        path,
        compression="gzip",
        usecols=["latest_lat", "latest_lon"],
        chunksize=200_000,
    ):
        valid = (
            chunk["latest_lat"].between(-90, 90)
            & chunk["latest_lon"].between(-180, 180)
            & ~((chunk["latest_lat"] == 0) & (chunk["latest_lon"] == 0))
        )
        chunk = chunk.loc[valid]
        if chunk.empty:
            continue
        ax.scatter(
            chunk["latest_lon"],
            chunk["latest_lat"],
            transform=plate,
            s=style["size"],
            marker=style["marker"],
            c=style["color"],
            alpha=style["alpha"],
            linewidths=0.45 if style["marker"] == "x" else 0,
            rasterized=True,
            zorder=style["zorder"],
        )
        plotted += len(chunk)
    return plotted


def make_plot(rows: list[dict[str, str]], output: Path) -> None:
    mpl.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Times New Roman", "Nimbus Roman", "DejaVu Serif"],
            "font.size": 7.2,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )

    projection = ccrs.Robinson(central_longitude=0)
    plate = ccrs.PlateCarree()
    fig = plt.figure(figsize=(7.0, 3.72))
    ax = fig.add_axes([0.015, 0.145, 0.97, 0.84], projection=projection)
    ax.set_global()
    ax.set_facecolor("#eaf1f5")
    ax.add_geometries(
        world_geometries(),
        crs=plate,
        facecolor="#f4f1e8",
        edgecolor="#8e8a82",
        linewidth=0.20,
        zorder=0,
    )

    plotted_counts = {group: 0 for group in GROUP_ORDER}
    for group in GROUP_ORDER:
        for row in rows:
            if row["figure_group"] != group:
                continue
            plotted_counts[group] += plot_cell_file(ax, plate, CELLS / f"{row['plmn']}.csv.gz", group)

    expected_counts = group_counts()
    mismatches = {
        group: (plotted_counts[group], expected_counts.get(group, 0))
        for group in GROUP_ORDER
        if plotted_counts[group] != expected_counts.get(group, 0)
    }
    if mismatches:
        raise RuntimeError(f"Plotted-point count does not match plmn_summary.csv: {mismatches}")

    handles = []
    for group in GROUP_ORDER:
        if not plotted_counts[group]:
            continue
        style = STYLE[group]
        handles.append(
            Line2D(
                [0],
                [0],
                linestyle="none",
                marker="o" if style["marker"] == "." else style["marker"],
                markerfacecolor=style["color"] if style["marker"] != "x" else "none",
                markeredgecolor=style["color"],
                markeredgewidth=0.8,
                markersize=5.2,
                label=f"{style['label']} ({plotted_counts[group]:,})",
            )
        )
    ax.legend(
        handles=handles,
        loc="lower center",
        bbox_to_anchor=(0.5, -0.125),
        ncol=2,
        frameon=True,
        facecolor="white",
        edgecolor="#b8b8b8",
        framealpha=0.96,
        fontsize=6.7,
        handletextpad=0.35,
        columnspacing=1.2,
        borderpad=0.42,
    )
    ax.spines["geo"].set_edgecolor("#777777")
    ax.spines["geo"].set_linewidth(0.45)

    output.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output, dpi=360, bbox_inches="tight", pad_inches=0.015)
    preview = output.with_suffix(".png")
    fig.savefig(preview, dpi=240, bbox_inches="tight", pad_inches=0.015)
    plt.close(fig)
    print(f"[figure] {output}")
    print(f"[preview] {preview}")
    print("[audit] " + ", ".join(f"{group}={plotted_counts[group]:,}" for group in GROUP_ORDER))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    from satellite_analysis_figures import configure, starlink_global_map

    configure()
    phenotypes = pd.read_csv(DATA / "plmn_phenotypes.csv")
    coverage = pd.read_csv(DATA / "tac_coverage.csv.gz", compression="gzip")
    starlink_global_map(phenotypes, coverage)
    generated = ROOT / "paper" / "figs" / "satellite_world_map.pdf"
    if args.output.resolve() != generated.resolve():
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_bytes(generated.read_bytes())


if __name__ == "__main__":
    main()
