#!/usr/bin/env python3
"""Raw-time validation for the remaining global spoofing screens.

The broad screens are generated by ``search_remaining_spoofing_modes.py``.
This program fetches only observations or members belonging to their finite
candidate sets.  Remote ClickHouse access goes through ``ch_remote.py`` and is
therefore forced to ``readonly=2``.
"""

from __future__ import annotations

import argparse
import itertools
from pathlib import Path

import numpy as np
import pandas as pd

from ch_remote import ch_df


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "spoofing" / "remaining_search"
KEY = ["mcc", "mnc", "lac", "cid", "cell_type"]
EARTH_KM = 6371.0088


def haversine(lat1, lon1, lat2, lon2):
    lat1 = np.radians(np.asarray(lat1, dtype=float))
    lon1 = np.radians(np.asarray(lon1, dtype=float))
    lat2 = np.radians(np.asarray(lat2, dtype=float))
    lon2 = np.radians(np.asarray(lon2, dtype=float))
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    return 2 * EARTH_KM * np.arctan2(np.sqrt(a), np.sqrt(np.maximum(1 - a, 0)))


def normalize_headers(frame: pd.DataFrame) -> pd.DataFrame:
    frame = frame.copy()
    frame.columns = [column.rsplit(".", 1)[-1] for column in frame.columns]
    return frame


def identity_tuples(frame: pd.DataFrame) -> str:
    return ",".join(
        f"({int(r.mcc)},{int(r.mnc)},{int(r.lac)},{int(r.cid)},'{r.cell_type}')"
        for r in frame[KEY].drop_duplicates().itertuples(index=False)
    )


def uid(frame: pd.DataFrame) -> pd.Series:
    return frame[KEY].astype(str).agg("/".join, axis=1)


def candidate_identities() -> pd.DataFrame:
    moving = pd.read_csv(OUTPUT / "moving_track_audit.csv")
    moving = moving[moving["passes_geometry"]].copy()
    moving["moving_candidate"] = True
    cycling = pd.read_csv(OUTPUT / "multidestination_identity_audit.csv")
    cycling = cycling[cycling["cycle_candidate"]].copy()
    cycling["cycling_candidate"] = True
    kinematic = normalize_headers(pd.read_csv(OUTPUT / "kinematic_interval_screen.csv"))
    kinematic = kinematic[KEY].drop_duplicates()
    kinematic["kinematic_candidate"] = True
    merged = moving[KEY + ["moving_candidate"]].merge(
        cycling[KEY + ["cycling_candidate"]], on=KEY, how="outer"
    ).merge(kinematic, on=KEY, how="outer")
    for column in ["moving_candidate", "cycling_candidate", "kinematic_candidate"]:
        merged[column] = merged[column].fillna(False).astype(bool)
    return merged


def fetch_raw(ids: pd.DataFrame, chunk_size: int = 150) -> pd.DataFrame:
    frames = []
    for start in range(0, len(ids), chunk_size):
        chunk = ids.iloc[start:start + chunk_size]
        print(f"raw observations: identities {start + 1}-{start + len(chunk)} of {len(ids)}", flush=True)
        tuples = identity_tuples(chunk)
        frame = ch_df(f"""
          SELECT mcc,mnc,lac,cid,toString(cell_type) AS cell_type,
                 timestamp,lat,lon
          FROM cell.geos
          PREWHERE (mcc,mnc,lac,cid,cell_type) IN ({tuples})
          WHERE lat BETWEEN -90 AND 90 AND lon BETWEEN -180 AND 180
            AND NOT(abs(lat)<=0.01 AND abs(lon)<=0.01)
          ORDER BY mcc,mnc,lac,cid,cell_type,timestamp
        """, settings={"max_threads": 4, "max_execution_time": 3600})
        frames.append(normalize_headers(frame))
    raw = pd.concat(frames, ignore_index=True)
    raw["timestamp"] = pd.to_datetime(raw["timestamp"])
    raw["plat"] = np.rint(raw["lat"] * 100).astype(int)
    raw["plon"] = np.rint(raw["lon"] * 100).astype(int)
    return raw


def selected_event_members() -> tuple[pd.DataFrame, pd.DataFrame]:
    short_events = pd.read_csv(OUTPUT / "short_range_raw_member_audit.csv")
    short_events = short_events[short_events.synchronized_persistent_candidate]
    short_key = ["src_lat10", "src_lon10", "onset_day", "plat", "plon"]
    short = pd.read_csv(OUTPUT / "short_range_candidate_members.csv.gz")
    short = short.merge(short_events[short_key], on=short_key, how="inner")

    small_events = pd.read_csv(OUTPUT / "small_cohort_raw_member_audit.csv")
    small_events = small_events[small_events.tight_synchronized_candidate]
    small_key = ["src_lat10", "src_lon10", "onset_day", "dest_lat5", "dest_lon5"]
    small = pd.read_csv(OUTPUT / "small_cohort_candidate_members.csv")
    small = small.merge(small_events[small_key], on=small_key, how="inner")
    return short, small


def raw_membership_pair_audit(
    raw: pd.DataFrame, members: pd.DataFrame, event_key: list[str],
    target_lat: str, target_lon: str, target_scale: float, prefix: str,
) -> pd.DataFrame:
    raw_groups = {key: group.sort_values("timestamp") for key, group in raw.groupby(KEY, sort=False)}
    rows = []
    for member in members.itertuples(index=False):
        identity = tuple(getattr(member, column) for column in KEY)
        group = raw_groups.get(identity)
        if group is None:
            continue
        ref_lat = member.hlat / 100 if hasattr(member, "hlat") else member.rlat / 100
        ref_lon = member.hlon / 100 if hasattr(member, "hlon") else member.rlon / 100
        destination_lat = getattr(member, target_lat) / target_scale
        destination_lon = getattr(member, target_lon) / target_scale
        home_distance = haversine(group.lat, group.lon, ref_lat, ref_lon)
        destination_distance = haversine(group.lat, group.lon, destination_lat, destination_lon)
        # Keep the two classes disjoint.  This matters below roughly 10 km:
        # otherwise one point inside overlapping radii can pair with itself and
        # masquerade as an exact dual-location observation.
        home = group[(home_distance <= 5) & (destination_distance > 1.5)]
        away = group[(destination_distance <= 1.5) & (home_distance > 5)]
        if home.empty or away.empty:
            continue
        home_seconds = home.timestamp.values.astype("datetime64[s]").astype("int64")
        away_seconds = away.timestamp.values.astype("datetime64[s]").astype("int64")
        nearest, gaps = nearest_indices(away_seconds, home_seconds)
        rows.append({column: getattr(member, column) for column in [*event_key, *KEY]} | {
            "home_raw_observations": len(home), "away_raw_observations": len(away),
            "minimum_home_away_gap_seconds": int(gaps.min()),
            "home_away_pairs_within_5m": int((gaps <= 300).sum()),
            "home_away_pairs_within_1h": int((gaps <= 3600).sum()),
            "exact_simultaneous": bool(np.any(gaps == 0)),
        })
    membership = pd.DataFrame(rows)
    membership.to_csv(OUTPUT / f"{prefix}_raw_membership_audit.csv", index=False)
    if membership.empty:
        event_audit = pd.DataFrame()
    else:
        event_audit = membership.groupby(event_key, as_index=False).agg(
            identities_with_raw_support=("cid", "size"),
            identities_with_pair_within_5m=("home_away_pairs_within_5m", lambda x: int((x > 0).sum())),
            identities_with_pair_within_1h=("home_away_pairs_within_1h", lambda x: int((x > 0).sum())),
            raw_home_observations=("home_raw_observations", "sum"),
            raw_away_observations=("away_raw_observations", "sum"),
            minimum_gap_seconds=("minimum_home_away_gap_seconds", "min"),
            exact_simultaneous_identities=("exact_simultaneous", "sum"),
        )
        event_audit["five_minute_pair_fraction"] = (
            event_audit.identities_with_pair_within_5m / event_audit.identities_with_raw_support
        )
        event_audit["one_hour_pair_fraction"] = (
            event_audit.identities_with_pair_within_1h / event_audit.identities_with_raw_support
        )
    event_audit.to_csv(OUTPUT / f"{prefix}_raw_event_audit.csv", index=False)
    return event_audit


def nearest_indices(left_seconds: np.ndarray, right_seconds: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    index = np.searchsorted(right_seconds, left_seconds)
    lo = np.clip(index - 1, 0, len(right_seconds) - 1)
    hi = np.clip(index, 0, len(right_seconds) - 1)
    nearest = np.where(
        np.abs(right_seconds[lo] - left_seconds) <= np.abs(right_seconds[hi] - left_seconds),
        lo, hi,
    )
    return nearest, np.abs(right_seconds[nearest] - left_seconds)


def validate_kinematics(raw: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    targets = normalize_headers(pd.read_csv(
        OUTPUT / "kinematic_interval_screen.csv",
        parse_dates=["away_first", "away_last", "home_first", "home_last"],
    ))
    raw_groups = {key: group.sort_values("timestamp") for key, group in raw.groupby(KEY, sort=False)}
    audits, pairs = [], []
    for row in targets.itertuples(index=False):
        key = tuple(getattr(row, column) for column in KEY)
        group = raw_groups.get(key)
        if group is None:
            continue
        home_distance = haversine(group.lat, group.lon, row.hlat / 100, row.hlon / 100)
        home = group[home_distance <= 5].copy()
        away = group[(group.plat == row.plat) & (group.plon == row.plon)].copy()
        if home.empty or away.empty:
            continue
        home_seconds = home.timestamp.values.astype("datetime64[s]").astype("int64")
        away_seconds = away.timestamp.values.astype("datetime64[s]").astype("int64")
        nearest, gaps = nearest_indices(away_seconds, home_seconds)
        speed = np.where(gaps == 0, np.inf, row.km / (gaps / 3600))
        qualifying = (gaps <= 3600) & (speed >= 900)
        for away_i in np.flatnonzero(qualifying):
            a = away.iloc[away_i]
            h = home.iloc[nearest[away_i]]
            pairs.append(dict(zip(KEY, key, strict=True)) | {
                "destination_lat": row.plat / 100, "destination_lon": row.plon / 100,
                "distance_km": row.km, "home_timestamp": h.timestamp,
                "away_timestamp": a.timestamp, "gap_seconds": int(gaps[away_i]),
                "implied_speed_kmh": float(speed[away_i]),
                "home_lat": h.lat, "home_lon": h.lon,
                "away_lat": a.lat, "away_lon": a.lon,
            })
        audits.append(dict(zip(KEY, key, strict=True)) | {
            "destination_lat": row.plat / 100, "destination_lon": row.plon / 100,
            "distance_km": row.km, "home_raw_observations": len(home),
            "away_raw_observations": len(away), "min_gap_seconds": int(gaps.min()),
            "max_implied_speed_kmh": float(np.max(speed)),
            "exact_simultaneous": bool(np.any(gaps == 0)),
            "impossible_pair_observations": int(qualifying.sum()),
            "impossible_pair_days": int(away.iloc[np.flatnonzero(qualifying)].timestamp.dt.date.nunique()),
        })
    audit = pd.DataFrame(audits)
    if not audit.empty:
        audit["raw_kinematic_positive"] = (
            audit["impossible_pair_observations"].ge(1)
            & (audit["exact_simultaneous"] | audit["impossible_pair_days"].ge(2))
        )
        audit = audit.sort_values(
            ["raw_kinematic_positive", "impossible_pair_days", "impossible_pair_observations", "distance_km"],
            ascending=False,
        )
    pair_frame = pd.DataFrame(pairs)
    audit.to_csv(OUTPUT / "kinematic_raw_audit.csv", index=False)
    pair_frame.to_csv(OUTPUT / "kinematic_impossible_pairs.csv", index=False)
    return audit, pair_frame


def moving_shared_destinations(raw: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    candidates = pd.read_csv(OUTPUT / "moving_track_audit.csv")
    candidates = candidates[candidates["passes_geometry"]].copy()
    refs = candidates.set_index(KEY)[["source_lat", "source_lon"]].to_dict("index")
    selected = raw.merge(candidates[KEY], on=KEY, how="inner")
    selected["identity"] = uid(selected)
    selected["source_lat"] = [refs[tuple(row)]["source_lat"] for row in selected[KEY].itertuples(index=False, name=None)]
    selected["source_lon"] = [refs[tuple(row)]["source_lon"] for row in selected[KEY].itertuples(index=False, name=None)]
    selected["distance_from_source_km"] = haversine(
        selected.lat, selected.lon, selected.source_lat, selected.source_lon
    )
    selected = selected[selected["distance_from_source_km"] >= 25].copy()
    selected["day"] = selected.timestamp.dt.floor("D")
    shared = selected.groupby(["day", "plat", "plon"]).agg(
        identities=("identity", "nunique"), distinct_cids=("cid", "nunique"),
        operators=("mnc", "nunique"), mccs=("mcc", "nunique"),
        source_lat_span=("source_lat", lambda x: x.max() - x.min()),
        source_lon_span=("source_lon", lambda x: x.max() - x.min()),
        observations=("identity", "size"), identity_list=("identity", lambda x: "|".join(sorted(set(x)))),
    ).reset_index()
    shared = shared[shared["identities"] >= 2].sort_values(
        ["identities", "day"], ascending=[False, True]
    )
    shared.to_csv(OUTPUT / "moving_shared_destination_days.csv", index=False)

    pair_counts: dict[tuple[str, str], int] = {}
    for identities in shared.identity_list:
        values = identities.split("|")
        for pair in itertools.combinations(values, 2):
            pair_counts[pair] = pair_counts.get(pair, 0) + 1
    pair_rows = [{"identity_a": a, "identity_b": b, "shared_destination_days": n}
                 for (a, b), n in pair_counts.items() if n >= 3]
    pair_frame = pd.DataFrame(
        pair_rows,
        columns=["identity_a", "identity_b", "shared_destination_days"],
    )
    if not pair_frame.empty:
        pair_frame = pair_frame.sort_values("shared_destination_days", ascending=False)
    pair_frame.to_csv(OUTPUT / "moving_shared_identity_pairs.csv", index=False)
    return shared, pair_frame


def validate_multidestination(raw: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    candidates = pd.read_csv(OUTPUT / "multidestination_identity_audit.csv")
    candidates = candidates[candidates["cycle_candidate"]].copy()
    refs = candidates.set_index(KEY)[["source_lat", "source_lon"]].to_dict("index")
    selected = raw.merge(candidates[KEY], on=KEY, how="inner")
    selected["identity"] = uid(selected)
    selected["source_lat"] = [refs[tuple(row)]["source_lat"] for row in selected[KEY].itertuples(index=False, name=None)]
    selected["source_lon"] = [refs[tuple(row)]["source_lon"] for row in selected[KEY].itertuples(index=False, name=None)]
    selected["distance_from_source_km"] = haversine(
        selected.lat, selected.lon, selected.source_lat, selected.source_lon
    )
    selected = selected[selected["distance_from_source_km"] >= 20].copy()
    audits, transitions = [], []
    for identity, group in selected.groupby("identity", sort=False):
        group = group.sort_values("timestamp")
        group = group.loc[group[["plat", "plon"]].ne(group[["plat", "plon"]].shift()).any(axis=1)]
        coords = list(zip(group.plat.astype(int), group.plon.astype(int), strict=True))
        cycle_count = 0
        for i in range(len(coords) - 2):
            for j in range(i + 2, len(coords)):
                if coords[i] == coords[j] and len(set(coords[i:j + 1])) >= 2:
                    cycle_count += 1
                    break
        for left, right in zip(group.iloc[:-1].itertuples(index=False), group.iloc[1:].itertuples(index=False)):
            transitions.append({
                "identity": identity, "mcc": left.mcc, "mnc": left.mnc,
                "transition_day": right.timestamp.floor("D"),
                "from_plat": left.plat, "from_plon": left.plon,
                "to_plat": right.plat, "to_plon": right.plon,
                "transition_hours": (right.timestamp - left.timestamp).total_seconds() / 3600,
            })
        first = group.iloc[0]
        audits.append({
            "identity": identity, "mcc": first.mcc, "mnc": first.mnc,
            "lac": first.lac, "cid": first.cid, "cell_type": first.cell_type,
            "raw_away_observations": len(group), "raw_destinations": len(set(coords)),
            "raw_return_cycles": cycle_count,
            "first_raw_destination": group.timestamp.min(),
            "last_raw_destination": group.timestamp.max(),
        })
    transition_frame = pd.DataFrame(transitions)
    if not transition_frame.empty:
        batches = transition_frame.groupby(
            ["transition_day", "from_plat", "from_plon", "to_plat", "to_plon"], as_index=False
        ).agg(
            identities=("identity", "nunique"), distinct_cids=("identity", "nunique"),
            operators=("mnc", "nunique"), mccs=("mcc", "nunique"),
            median_transition_hours=("transition_hours", "median"),
        )
        batches = batches[batches.identities >= 2].sort_values(
            ["identities", "transition_day"], ascending=[False, True]
        )
    else:
        batches = pd.DataFrame()
    audit = pd.DataFrame(audits)
    audit.to_csv(OUTPUT / "multidestination_raw_sequence_audit.csv", index=False)
    batches.to_csv(OUTPUT / "multidestination_shared_transitions.csv", index=False)
    return audit, batches


def event_tuples(frame: pd.DataFrame, columns: list[str]) -> str:
    values = []
    for row in frame[columns].drop_duplicates().itertuples(index=False, name=None):
        formatted = []
        for column, value in zip(columns, row, strict=True):
            if column == "onset_day":
                formatted.append(f"toDate('{pd.Timestamp(value).date()}')")
            else:
                formatted.append(str(int(value)))
        values.append("(" + ",".join(formatted) + ")")
    return ",".join(values)


def fetch_short_members(events: pd.DataFrame) -> pd.DataFrame:
    columns = ["src_lat10", "src_lon10", "onset_day", "plat", "plon"]
    selected = event_tuples(events, columns)
    return normalize_headers(ch_df(f"""
      SELECT p.mcc,p.mnc,p.lac,p.cid,toString(p.cell_type) cell_type,
             intDiv(h.hlat,10) src_lat10,intDiv(h.hlon,10) src_lon10,
             toDate(p.first_seen) onset_day,p.plat,p.plon,p.obs,
             p.first_seen,p.last_seen,h.hlat,h.hlon,
             r.obs home_reference_obs,r.m_first home_first_month,
             r.m_last home_last_month,r.n_months,s.stab_frac,
             greatCircleDistance(p.plon/100,p.plat/100,h.hlon/100,h.hlat/100)/1000 distance_km
      FROM cell.cellpos p
      INNER JOIN cell.cellhome h USING (mcc,mnc,lac,cid,cell_type)
      INNER JOIN spoof.cellref r USING (mcc,mnc,lac,cid,cell_type)
      INNER JOIN spoof.cellref_stability s USING (mcc,mnc,lac,cid,cell_type)
      WHERE p.cid>0 AND p.obs>=2 AND r.n_months>=4 AND s.stab_frac>=0.7
       AND (intDiv(h.hlat,10),intDiv(h.hlon,10),toDate(p.first_seen),p.plat,p.plon) IN ({selected})
    """, settings={"max_threads": 6, "max_execution_time": 7200}))


def audit_short_members(members: pd.DataFrame) -> pd.DataFrame:
    event_key = ["src_lat10", "src_lon10", "onset_day", "plat", "plon"]
    for column in ["first_seen", "last_seen", "home_first_month", "home_last_month"]:
        members[column] = pd.to_datetime(members[column])
    members["home_active_at_onset"] = (
        (members.home_first_month <= members.first_seen)
        & (members.home_last_month + pd.offsets.MonthEnd(0) >= members.first_seen)
    )
    members["home_after"] = members.home_last_month + pd.offsets.MonthEnd(0) > members.first_seen
    members["onset_hour"] = members.first_seen.dt.floor("h")
    rows = []
    for key, group in members.groupby(event_key, sort=False):
        hour_counts = group.groupby("onset_hour")[KEY].size()
        identities = group[KEY].drop_duplicates().shape[0]
        rows.append(dict(zip(event_key, key, strict=True)) | {
            "identities": identities, "distinct_cids": group.cid.nunique(),
            "operators": group[["mcc", "mnc"]].drop_duplicates().shape[0],
            "technologies": group.cell_type.nunique(), "observations": int(group.obs.sum()),
            "median_km": group.distance_km.median(),
            "first_onset": group.first_seen.min(), "last_onset": group.first_seen.max(),
            "onset_span_hours": (group.first_seen.max() - group.first_seen.min()).total_seconds() / 3600,
            "largest_onset_hour": hour_counts.idxmax(),
            "largest_onset_hour_fraction": hour_counts.max() / identities,
            "home_active_fraction": group.home_active_at_onset.mean(),
            "home_after_fraction": group.home_after.mean(),
            "median_reference_stability": group.stab_frac.median(),
        })
    audit = pd.DataFrame(rows)
    audit["synchronized_persistent_candidate"] = (
        audit.distinct_cids.ge(10)
        & ((audit.operators >= 2) | (audit.technologies >= 2))
        & audit.median_km.ge(10)
        & audit.largest_onset_hour_fraction.ge(0.8)
        & audit.home_active_fraction.ge(0.8)
        & audit.home_after_fraction.ge(0.8)
    )
    audit.sort_values(
        ["synchronized_persistent_candidate", "distinct_cids", "observations"], ascending=False
    ).to_csv(OUTPUT / "short_range_raw_member_audit.csv", index=False)
    members.to_csv(OUTPUT / "short_range_candidate_members.csv.gz", index=False, compression="gzip")
    return audit


def fetch_small_members(events: pd.DataFrame) -> pd.DataFrame:
    columns = ["src_lat10", "src_lon10", "onset_day", "dest_lat5", "dest_lon5"]
    selected = event_tuples(events, columns)
    return normalize_headers(ch_df(f"""
      SELECT o.mcc,o.mnc,o.lac,o.cid,toString(o.cell_type) cell_type,
             o.src_lat10,o.src_lon10,o.onset_day,o.onset_ts,
             intDiv(o.top_plat,5)*5 dest_lat5,intDiv(o.top_plon,5)*5 dest_lon5,
             o.top_plat,o.top_plon,o.away_obs,o.med_km,o.max_km,
             r.rlat,r.rlon,r.n_months,s.stab_frac
      FROM spoof.onsets_f o
      INNER JOIN spoof.cellref r USING (mcc,mnc,lac,cid,cell_type)
      INNER JOIN spoof.cellref_stability s USING (mcc,mnc,lac,cid,cell_type)
      WHERE o.cid>0 AND o.med_km>=100 AND r.n_months>=4 AND s.stab_frac>=0.7
       AND (o.src_lat10,o.src_lon10,o.onset_day,
            intDiv(o.top_plat,5)*5,intDiv(o.top_plon,5)*5) IN ({selected})
    """, settings={"max_threads": 4, "max_execution_time": 3600}))


def audit_small_members(members: pd.DataFrame) -> pd.DataFrame:
    event_key = ["src_lat10", "src_lon10", "onset_day", "dest_lat5", "dest_lon5"]
    members["onset_ts"] = pd.to_datetime(members.onset_ts)
    rows = []
    for key, group in members.groupby(event_key, sort=False):
        identities = group[KEY].drop_duplicates()
        rows.append(dict(zip(event_key, key, strict=True)) | {
            "identities": len(identities), "distinct_cids": group.cid.nunique(),
            "operators": identities[["mcc", "mnc"]].drop_duplicates().shape[0],
            "technologies": group.cell_type.nunique(), "away_observations": int(group.away_obs.sum()),
            "first_onset": group.onset_ts.min(), "last_onset": group.onset_ts.max(),
            "onset_span_minutes": (group.onset_ts.max() - group.onset_ts.min()).total_seconds() / 60,
            "median_km": group.med_km.median(),
            "source_lat": group.rlat.median() / 100, "source_lon": group.rlon.median() / 100,
            "destination_lat": group.top_plat.median() / 100,
            "destination_lon": group.top_plon.median() / 100,
            "source_radius_p90_km": np.quantile(haversine(
                group.rlat / 100, group.rlon / 100, group.rlat.median() / 100, group.rlon.median() / 100
            ), .9),
            "destination_radius_p90_km": np.quantile(haversine(
                group.top_plat / 100, group.top_plon / 100,
                group.top_plat.median() / 100, group.top_plon.median() / 100
            ), .9),
        })
    audit = pd.DataFrame(rows)
    audit["tight_synchronized_candidate"] = (
        audit.distinct_cids.ge(2) & ((audit.operators >= 2) | (audit.technologies >= 2))
        & audit.onset_span_minutes.le(60) & audit.source_radius_p90_km.le(50)
        & audit.destination_radius_p90_km.le(5)
    )
    audit.sort_values(
        ["tight_synchronized_candidate", "distinct_cids", "away_observations"], ascending=False
    ).to_csv(OUTPUT / "small_cohort_raw_member_audit.csv", index=False)
    members.to_csv(OUTPUT / "small_cohort_candidate_members.csv", index=False)
    return audit


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--refresh-raw", action="store_true")
    parser.add_argument("--refresh-event-members", action="store_true")
    parser.add_argument("--refresh-event-raw", action="store_true")
    args = parser.parse_args()
    OUTPUT.mkdir(parents=True, exist_ok=True)

    raw_path = OUTPUT / "raw_candidate_observations.csv.gz"
    if args.refresh_raw:
        raw = fetch_raw(candidate_identities())
        raw.to_csv(raw_path, index=False, compression="gzip")
    else:
        raw = pd.read_csv(raw_path, parse_dates=["timestamp"])
    validate_kinematics(raw)
    moving_shared_destinations(raw)
    validate_multidestination(raw)

    short_events = pd.read_csv(OUTPUT / "short_range_event_audit.csv", parse_dates=["onset_day"])
    short_events = short_events[short_events.high_signal]
    short_member_path = OUTPUT / "short_range_candidate_members.csv.gz"
    small_events = pd.read_csv(OUTPUT / "small_cohort_event_audit.csv", parse_dates=["onset_day"])
    small_events = small_events[small_events.coordinated_candidate]
    small_member_path = OUTPUT / "small_cohort_candidate_members.csv"
    if args.refresh_event_members:
        short_members = fetch_short_members(short_events)
        small_members = fetch_small_members(small_events)
    else:
        short_members = pd.read_csv(short_member_path)
        small_members = pd.read_csv(small_member_path)
    short_audit = audit_short_members(short_members)
    small_audit = audit_small_members(small_members)

    short_selected, small_selected = selected_event_members()
    event_raw_path = OUTPUT / "event_candidate_observations.csv.gz"
    if args.refresh_event_raw:
        event_ids = pd.concat([short_selected[KEY], small_selected[KEY]]).drop_duplicates()
        event_raw = fetch_raw(event_ids)
        event_raw.to_csv(event_raw_path, index=False, compression="gzip")
    elif event_raw_path.exists():
        event_raw = pd.read_csv(event_raw_path, parse_dates=["timestamp"])
    else:
        event_raw = None
    if event_raw is not None:
        raw_membership_pair_audit(
            event_raw, short_selected,
            ["src_lat10", "src_lon10", "onset_day", "plat", "plon"],
            "plat", "plon", 100, "short_range",
        )
        raw_membership_pair_audit(
            event_raw, small_selected,
            ["src_lat10", "src_lon10", "onset_day", "dest_lat5", "dest_lon5"],
            "top_plat", "top_plon", 100, "small_cohort",
        )
    print({
        "raw_observations": len(raw),
        "kinematic_targets": len(pd.read_csv(OUTPUT / "kinematic_raw_audit.csv")),
        "short_range_events_validated": len(short_audit),
        "small_cohort_events_validated": len(small_audit),
    })


if __name__ == "__main__":
    main()
